# Extension -> comment-style mapping used by add-license-headers.sh.
# One "ext style" pair per line. Extensions not listed here are skipped.
# Styles: slash (//), hash (#), block (/* */), html (<!-- -->), jinja ({# #})
#
# A repo can override this file by placing its own copy at scripts/license-comment-styles.conf.

js      slash
jsx     slash
ts      slash
tsx     slash
mjs     slash
cjs     slash

py      hash
sh      hash
bash    hash
yml     hash
yaml    hash
ftl     hash

css     block
scss    block
less    block

html    html
htm     html
vue     html

jinja2  jinja
j2      jinja
